"""The optimization study's report: figures and README come from results only."""

from __future__ import annotations

import pytest

pytest.importorskip("torch")

from physprior.optim import report as R


def test_render_doc_without_results_writes_method_only(tmp_settings, tmp_path):
    out = tmp_path / "README.md"
    text = R.render_doc(out)
    assert out.read_text() == text
    assert "Generated by physprior.optim.report.render_doc()" in text
    assert "| model |" not in text  # no result tables without results


def test_scratch_results_render(tmp_settings, tmp_path):
    R.run_scratch(quick=True)
    R.make_figures()  # skips what is missing, draws what is there
    text = R.render_doc(tmp_path / "README.md")
    assert "Backprop against torch autograd" in text
    assert (
        tmp_settings.figures_dir / "optim" / "01_scratch_optimizers_gradcheck.png"
    ).exists()


@pytest.mark.slow
def test_quick_optimizer_study_end_to_end(tmp_settings, tmp_path):
    from physprior.optim import optimizers_study as O

    O.run(quick=True, tasks=("oscillator",), workers=1)
    R.make_figures()
    text = R.render_doc(tmp_path / "README.md")
    assert "damped oscillator (ODE)" in text
    assert "evals to tol" in text
