"""docs/SUMMARY.md: the project on one page, generated from results/.

    physprior summary-md [--check]

Every number on the page is read from a results file when it is written; the
prose around them describes method and says which way a result points, never
how large it is. `tests/test_project_summary.py` fails if the committed page
differs from a fresh render.
"""

from __future__ import annotations

import json

from physprior.config import get_settings

PAGE = "SUMMARY.md"


def _pct(v: float, nd: int = 2) -> str:
    return f"{100 * float(v):.{nd}g} %"


def _g(v: float, nd: int = 3) -> str:
    return f"{float(v):.{nd}g}"


def _constants_rows() -> list[str]:
    p = get_settings().results_dir / "headline.json"
    if not p.exists():
        return []
    rows = json.loads(p.read_text()).get("parameter_recovery", [])
    out = [
        "| track | quantity | published | recovered | deviation |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        rec = r.get("recovered")
        out.append(
            f"| {r['track']} | {r['quantity']} | {_g(r['published'], 8)} | "
            f"{_g(rec, 8) if rec is not None else '–'} | {r['deviation']} |"
        )
    return out


PIPELINE = """```mermaid
flowchart LR
  subgraph data [Data]
    R[real measurements<br/>LIGO, NASA, NIST, JPL, ATNF, NOAA]
    SIM[simulations<br/>law known exactly]
  end
  subgraph arms [Arms, same splits and seeds]
    O[oracle: published law]
    PH[physics: law, constants fitted]
    PI[PINN: law + network]
    SR[symbolic regression]
    NN[black-box NN, tuned]
  end
  subgraph proto [Protocol]
    Q1[interpolation]
    Q2[data budget]
    Q3[noise]
    Q4[extrapolation]
    Q5[constants]
    Q6[law recovery]
  end
  R --> arms
  SIM --> arms
  arms --> proto
  proto --> RES[results/*.csv<br/>tuned on seeds 3,7,19<br/>reported on 11,23,42]
  RES --> DOCS[generated docs, figures, notebooks]
```"""

PINN_DIAGRAM = """```mermaid
flowchart LR
  t[time t] --> FF[Fourier features] --> MLP[MLP, tanh] --> U["u(t)"]
  U --> LD["L_data vs noisy observations"]
  MLP -- "forward-mode du/dt" --> RES["du/dt - f(u; sigma, rho, beta)"]
  U --> RES
  TH["sigma, rho, beta (trained)"] --> RES
  RES --> LP[L_phys]
  LD --> L["L = L_data + w(k) L_phys"]
  LP --> L
  L --> OPT["Adam (cosine lr, warm-up + ramp) then L-BFGS"]
```"""


def render(path=None) -> str:
    from physprior.lorenz import doc as LD

    f = LD.findings()
    lad = LD.ladder_table()
    noise = LD.sweep_table("noise", "noise")
    nn_col = "black-box NN: trajectory"
    pinn_col = "PINN: trajectory"
    noise_lines = ["| noise | black-box NN | PINN | factor |", "|---|---|---|---|"]
    for _, r in noise.iterrows():
        noise_lines.append(
            f"| {_pct(r['noise'])} | {_g(r[nn_col])} | {_g(r[pinn_col])} | "
            f"{_g(r[nn_col] / r[pinn_col], 2)} |"
        )
    lad_lines = [
        "| recipe | trajectory error | worst seed | constants error |",
        "|---|---|---|---|",
    ]
    for _, r in lad.iterrows():
        lad_lines.append(
            f"| {r['recipe']} | {_g(r['trajectory error'])} | "
            f"{_g(r['worst seed, trajectory'])} | "
            f"{_pct(r['constants error'])} |"
        )
    budget = f["budget_ratio"]
    parts = [
        "# Summary",
        "",
        "*Generated by `physprior summary-md` from `results/`; do not edit by hand.*",
        "",
        "## The question",
        "",
        "What is a physics prior worth to a machine-learning model, and what "
        "does it cost when the law is wrong? Every study here compares models "
        "that know a law (the fitted law, a physics-informed network, symbolic "
        "regression) with a tuned black-box network, on the same data, splits "
        "and seeds. Half of the data is real measurement; the other half is "
        "simulation, where the law is known exactly and every error is the "
        "method's own.",
        "",
        PIPELINE,
        "",
        "## Where the physics-informed network pays: a chaotic inverse problem",
        "",
        "![the butterfly effect](figures/lorenz/butterfly.gif)",
        "",
        f"{f['n_obs']} noisy observations of one Lorenz-63 trajectory, "
        f"{f['t_end'] * f['lambda_ref']:.1f} Lyapunov times long. The PINN fits "
        "the trajectory and the three constants of the law together:",
        "",
        PINN_DIAGRAM,
        "",
        "![block diagram](figures/lorenz/block_diagram.png)",
        "",
        "Against a black-box network of the same kind, tuned on separate seeds:",
        "",
        "| | black-box NN | PINN |",
        "|---|---|---|",
        f"| trajectory error (normalised RMSE) | {_g(f['state_nn'])} | "
        f"{_g(f['state_pinn'])} |",
        f"| improvement | | {f['state_ratio']:.1f}x, on {f['wins_state']} of "
        f"{f['n_seeds']} seeds |",
        f"| du/dt error, improvement | | {f['deriv_ratio']:.1f}x |",
        f"| constants (sigma, rho, beta) | {_pct(f['theta_nn_regress'])} "
        f"(differentiate, then regress) | {_pct(f['theta_pinn'])} |",
        f"| valid forecast, Lyapunov times | {_g(f['vpt_nn'], 2)} (extrapolated) | "
        f"{_g(f['vpt_pinn'], 2)} (law with fitted constants) |",
        "",
        "Against classical fitting of the same law, from the same wrong start: "
        f"single shooting misses the constants by {_pct(f['theta_shooting'], 3)}; "
        f"multiple shooting recovers them to {_pct(f['theta_ms'])}; single "
        f"shooting started from the PINN's answer reaches "
        f"{_pct(f['theta_polish'])}. A well-built classical fit is as good as "
        "the PINN on the constants. The PINN needs no segmentation, returns a "
        "smooth trajectory and derivative, and gives shooting a start in the "
        "right basin.",
        "",
        "![every method](figures/lorenz/main.png)",
        "",
        "### Noise",
        "",
        *noise_lines,
        "",
        "The black box cannot interpolate a chaotic trajectory between "
        f"{f['n_obs']} points even without noise, while the PINN's error scales "
        "with the noise, so the factor is largest on clean data. With fewer "
        f"observations it is {budget[max(budget)]:.1f} at {max(budget):g} points "
        f"and {max(budget.values()):.0f} at "
        f"{max(budget, key=budget.get):g}. At {min(budget):g} points only the "
        "PINN still recovers the constants: "
        f"{_pct(f['budget_theta_pinn'][min(budget)])}, against "
        f"{_pct(f['budget_theta_ms'][min(budget)])} for multiple shooting.",
        "",
        "![noise sweep](figures/lorenz/noise.png)",
        "",
        "### Making the PINN train",
        "",
        *lad_lines,
        "",
        f"A vanilla PINN fails on {f['vanilla_fails']} of {f['n_seeds']} seeds: "
        "it stalls in a minimum that fits neither the data nor the law. Fitting "
        "the data first and ramping the physics weight in is the change that "
        "matters most; a cosine learning rate, fresh collocation points each "
        "step, an L-BFGS finish and Fourier features of time tighten the worst "
        "seed. Gradient-norm balancing rescues most of the vanilla recipe; "
        "causal weighting adds nothing to the final one. The time derivative is "
        f"propagated in forward mode by hand, {f['speedup_forward']:.1f}x "
        "cheaper per step than reverse-mode autograd, and `torch.compile` gives "
        f"a further {f['compile_gain']:.2f}x.",
        "",
        "![loss terms](figures/lorenz/loss_breakdown.png)",
        "",
        "### The butterfly effect",
        "",
        f"Trajectories that start 1e-8 apart separate at the rate "
        f"{f['lambda_fit']:.3f} per unit time (reference lambda_1 = "
        f"{f['lambda_ref']}), and every forecast inherits that: an error e in "
        "the state reaches the validity threshold in about ln(0.4/e)/lambda_1, "
        "whatever produced it.",
        "",
        "![separation](figures/lorenz/separation.png)",
        "",
        "Full page: [docs/lorenz](docs/lorenz/README.md). Tutorial: "
        "[T14](notebooks/tutorials/T14_butterfly_and_the_pinn.ipynb).",
        "",
        "## What the other studies found",
        "",
        "Each line is a conclusion from the page it links to, where the numbers "
        "are generated from `results/`.",
        "",
        "- **In range, with enough clean data, a tuned black box is competitive.** "
        "The prior buys little there ([RESULTS](docs/RESULTS.md)).",
        "- **A learned correction pays when the law is incomplete in a way the "
        "law cannot imitate** ([neglected terms](docs/neglected/README.md)). "
        "When the missing term has the law's own shape, the fitted constant "
        "absorbs it and comes out wrong while the curve looks right.",
        "- **Goodness of fit does not diagnose a wrong law.** GW150914 at "
        "Newtonian order gives a biased chirp mass with barely a change in "
        "RMSE ([relativity](docs/relativity/README.md)).",
        "- **The network eats the physics if the physics weight is zero.** The "
        "constants drift while held-out error hardly moves "
        "([optimization](docs/optimization/README.md)).",
        "- **The prior's advantage grows with dimension** in field "
        "reconstruction from sparse sensors ([reconstruction]"
        "(docs/reconstruction/README.md)).",
        "- **Structure in a learned time-stepper keeps energy bounded** where "
        "black boxes drift ([dynamics](docs/dynamics/README.md)).",
        "- **The operator set is a prior for symbolic regression**: a law "
        "outside it is not found ([theory](docs/theory/symbolic_regression.md)).",
        "",
        "Every mission with its goal and conclusion: [MISSIONS](docs/MISSIONS.md). "
        "What is new: [CONTRIBUTIONS](docs/CONTRIBUTIONS.md). A tour in plots: "
        "[summary notebook](notebooks/summary.ipynb).",
        "",
        "## Constants recovered from real data",
        "",
        *_constants_rows(),
        "",
        "## Limits",
        "",
        "- The Lorenz study is a simulation with the law known exactly; it "
        "measures the method, not a discovery.",
        "- On algebraic laws that are already right, the PINN's correction "
        "extrapolates worse than the fitted law; helium refutes the prediction "
        "stated for it ([HYPOTHESES](docs/HYPOTHESES.md)).",
        "- Every number is on CPU in float64; the GPU paths are written but not "
        "used for results ([tools](tools/README.md)).",
        "",
        "## Reproduce",
        "",
        "```bash",
        "pip install -e '.[all]'",
        "physprior run all && physprior report     # the benchmark tracks",
        "physprior lorenz                          # the Lorenz study",
        "physprior tutorials --execute             # T1-T14",
        "physprior summary --execute               # the summary notebook",
        "make reproduce                            # re-run and compare every number",
        "```",
        "",
    ]
    # written in docs/, so links are relative to it
    text = "\n".join(parts)
    for a, b in (
        ("](docs/", "]("),
        ("](figures/", "](../figures/"),
        ("](notebooks/", "](../notebooks/"),
        ("](tools/", "](../tools/"),
    ):
        text = text.replace(a, b)
    out = path or get_settings().root / "docs" / PAGE
    out.write_text(text)
    return text


def check() -> bool:
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as d:
        fresh = render(Path(d) / PAGE)
    committed = (get_settings().root / "docs" / PAGE).read_text()
    return fresh == committed
