"""Fixed prose for docs/theory/, filled with result blocks by `report.render_doc`.

Method only. No result numbers are typed here: every number on the rendered
pages comes from results/symbolic/. Literal braces are doubled (str.format).
"""

SR_TEMPLATE = r"""# How symbolic regression works

<!-- Generated by physprior.symbolic.report.render_doc() from results/symbolic/.
     Edit src/physprior/symbolic/text.py, not this file. -->

Symbolic regression (SR) looks for a closed-form expression `f(x)` that fits
data, choosing both the form and its constants. It is the `sr` arm of this
project (`src/physprior/methods/symbolic.py`, which drives PySR). This page
explains how it works, from the size of the problem to the specific choices
PySR makes, and measures each claim with a small implementation in
`src/physprior/symbolic/`:

| module | what it is |
|---|---|
| `expressions.py` | expression trees, evaluation, complexity, constant fitting, the Pareto front and PySR's selection rules |
| `enumerate.py` | exact counts of the search space; exhaustive search with constant fitting |
| `gp.py` | a small genetic-programming SR |
| `sindy.py` | sparse regression of dynamics (STLSQ), with the derivative studies |
| `studies.py` | the experiments below; `report.py` renders this page |

Notebook: T11, `physprior.reporting.tutorials_sr.t11_how_symbolic_regression_works`.

## 1 · Two problems in one

A candidate law is a tree: internal nodes are operators, leaves are input
variables or free constants. `c0 - c1/square(n)` is Bohr's formula in six
nodes. SR therefore has to solve

1. a **discrete** problem, which tree; and
2. a **continuous** problem, which constants for that tree.

Every method here treats the second as ordinary least squares for a fixed
form, and differs in how it searches the first. The loss throughout is the
weighted mean squared error; with weights `1/y^2` it is the mean squared
*relative* error, which suits laws spanning decades (Kepler's periods).

**Complexity** is the node count, the default in PySR
(`compute_complexity` falls back to `count_nodes` in SymbolicRegression.jl
unless `complexity_of_operators`/`complexity_of_constants` are set).

## 2 · The size of the search space

With `L` leaf types, `U` unary and `B` binary operators, the number of
distinct trees of size `s` is

    T(1) = L
    T(s) = U T(s-1) + B sum_{{i+j=s-1}} T(i) T(j)

The binary term is a convolution of the same kind that produces the Catalan
numbers, so `T(s)` grows geometrically with a ratio that itself grows with
the vocabulary. Every tree with a constant needs its own nonlinear fit, so
the cost of exhaustive search is the count times a least-squares solve.
`enumerate.py` generates the trees and the tests check the enumeration
against the recurrence exactly.

{growth}

Exhaustive search is exact and complete up to its size cap and hopeless
beyond it: every added node multiplies the work by roughly the ratio in the
table, and every added operator raises that ratio. Many laws of interest need
more nodes than the cap. That is why every practical SR method is a heuristic
search, and why they all return the same kind of object: a list of the best
expressions found at each complexity.

## 3 · Genetic programming

Genetic programming (Koza 1992) keeps a **population** of trees and improves
it by selection and variation:

- **Selection.** A tournament samples `k` members and picks the one with the
  lowest cost. Cost = loss plus a **parsimony** penalty proportional to
  complexity, without which trees grow without bound ("bloat").
- **Crossover.** Replace a random subtree of one parent by a random subtree
  of another.
- **Mutation.** Change one node's label keeping its arity (point mutation),
  replace a subtree by a random one (subtree mutation), or perturb the
  constants.
- **Constants.** Evolving constants by mutation is slow and imprecise.
  Modern SR fits them with a local optimiser for each candidate form.
- **Hall of fame.** Keep the best expression ever seen at each complexity.
  Sorted by complexity with loss strictly decreasing, this is the **Pareto
  front** of loss against complexity, and it is the output of the search.

`gp.py` implements exactly this: ramped half-and-half initialisation;
tournament selection on `loss/baseline + parsimony * size`; subtree
crossover, subtree and point mutation, constant perturbation; every new
structure's constants fitted once by Levenberg-Marquardt (or BFGS) with a
restart, cached by structure; the front re-injected into each generation;
and a stop a few generations after the front reaches the measurement-noise
floor (the searchers know the error bars, not the law).

## 4 · How PySR does it

PySR is a Python front end to the Julia package SymbolicRegression.jl
(Cranmer 2023, arXiv:2305.01582). What follows was read from the installed
sources, PySR 2.5.0 (`pysr/sr.py`) and SymbolicRegression.jl 2.4.1 (the
version resolved in PySR's Julia environment), and names the file where
each behaviour lives. Defaults are PySR's, per its documentation strings.

**Islands.** The search runs `populations` (default 31) independent
populations of `population_size` (27) members. Each outer `niterations`
step (default 100) evolves every population for `ncycles_per_iteration`
(380) cycles, then **migrates**: a fraction of each population is replaced
by copies of the best members of the others (`fraction_replaced`,
0.00036) and of the hall of fame (`fraction_replaced_hof`, 0.0614)
(`Migration.jl`, `migrate!` draws the number replaced from a Poisson).

**Regularized (age-based) evolution.** Within a cycle
(`RegularizedEvolution.jl`, `reg_evol_cycle`), each step either mutates one
tournament winner (probability 1 - `crossover_probability`, default
1 - 0.2) or crosses two winners. The child replaces the **oldest** member of
the population, not the worst. Selection pressure comes only from the
tournament.

**Tournament.** `tournament_selection_n` (15) members are sampled; the best
is chosen with probability `p = tournament_selection_p` (0.982), otherwise
the k-th best with weight `p (1-p)^k` (`Population.jl`,
`_best_of_sample`). Costs are first multiplied by the adaptive-parsimony
factor below.

**Cost.** `loss / baseline + parsimony * complexity` (`LossFunctions.jl`,
`loss_to_cost`), where the baseline is the loss of a constant expression
(floored at 0.01) and `parsimony` defaults to 0. Parsimony is instead
applied **adaptively**: PySR tracks how often each complexity occurs in the
populations and, in the tournament, multiplies a member's cost by
`exp(adaptive_parsimony_scaling * frequency)` (scaling 1040;
`plugins/AdaptiveParsimony.jl`). Crowded complexities are penalised, so the
search keeps exploring all sizes rather than a fixed trade-off.

**Simulated-annealing acceptance.** A mutated child is kept with
probability `exp(-(cost_new - cost_old) / (T * alpha))` times
`frequency(old size) / frequency(new size)`, capped at 1 by the comparison
against one uniform draw (`Mutate.jl` multiplies the plugins' factors;
`plugins/SimulatedAnnealing.jl`, `plugins/AdaptiveParsimony.jl`). The
temperature `T` falls linearly from 1 to 0 over the cycles of each
iteration, so early cycles accept worse children and late ones are greedy.
PySR's `alpha` defaults to 3.17 (`annealing=True`). With the default
`skip_mutation_failures=True` a rejected mutation changes nothing: no member
is replaced.

**Mutations.** Chosen with relative weights (PySR defaults): add a node
2.47, delete 0.870, insert 0.0112, rotate the tree 4.26, mutate an operator
0.293, swap operands 0.198, mutate a feature 0.1, perturb a constant 0.0346
(scaled by the temperature), do nothing 0.273, simplify 0.00209, randomise
the whole tree 0.000502.

**Constants.** At the end of each iteration every member has its constants
optimised with probability `optimize_probability` (0.14): BFGS by default,
Newton when there is a single constant (`ConstantOptimization.jl`), for
`optimizer_iterations` (8) steps, from the current values plus
`optimizer_nrestarts` (2) restarts at `x0 * (1 + eps/2)`, `eps ~ N(0,1)`;
the result is kept only if it lowers the loss. Trees are also simplified
algebraically with a few rules when `should_simplify=True`.

**Hall of fame and the returned table.** The hall of fame holds the best
member seen at each complexity (`HallOfFame.jl`). `equations_` is its Pareto
frontier: complexity, loss, the expression, and a **score**,

    score_i = -log(loss_i / loss_(i-1)) / (complexity_i - complexity_(i-1)),   score_1 = 0

(`calculate_scores` in `pysr/sr.py`): the fractional drop in loss bought
per added node. `model_selection` then picks one row (`idx_model_selection`):

- `"accuracy"`: lowest loss;
- `"score"`: highest score;
- `"best"` (default): highest score **among rows with loss <= 1.5 x the
  lowest loss**.

"best" guards against choosing a very simple expression that happens to
have a large score but is much worse than the most accurate row. The flip
side is measured below: when the most complex rows fit the noise, the 1.5x
window excludes the law and "best" picks an over-fitted expression.
`expressions.select` implements the three rules with the same arithmetic,
and the tests check it.

**What this means for the repo.** The wrapper (`methods/symbolic.py`) runs
PySR with `deterministic=True, parallelism="serial"` and an explicit
`random_state`, so a cached search is reproducible; this page's PySR runs do
the same with a short budget, recorded in `results/symbolic/recovery_pysr_meta.json`.

**Where the in-repo GP differs.** One population (no islands, no
migration); generational replacement with the front as elite, not age-based;
no annealing; a fixed parsimony (chosen on tuning seeds) rather than
adaptive parsimony; every new structure has its constants fitted (cached),
not 14 % per iteration; Levenberg-Marquardt by default rather than BFGS; no
algebraic simplification; pure Python, so orders of magnitude slower per
evaluation. It is here to make the algorithm visible and to be measured next
to PySR and to exhaustive search on the same data.

## 5 · Measured: recovering laws from this repository

Four laws, each at the scale where it appears in the repo's tracks:

| law | form | nodes (default vocabulary) |
|---|---|---|
| Kepler III | `P = a^(3/2)`, years and AU, a in 0.39-5.2 | 3 (`sqrt(cube(a))`) |
| inverse square | `g = GM_sun / r^2`, mm/s^2 and AU | 4 |
| Bohr | `nu = R_H (1 - 1/n^2)`, 1e5 cm^-1, n = 2, 3, ... | 6 |
| Planck | `B = x^3/(e^x - 1)`, `x = h nu / k T` in 0.5-8 | 7 |

Vocabulary: `+ - * /` and `sqrt square cube exp log`, the repo's PySR
default. Noise is relative and Gaussian. A law counts as **recovered** when
the selected expression's form, with its constants freed, reproduces the
exact law to 1e-4 relative RMS on a grid reaching far outside the data
(`studies.form_check`), **and** the expression as fitted is within 5 % of
the law everywhere on that grid. The first condition is about the form, the
second rejects bloated forms that nest the law but carry nonsense extra
terms. As elsewhere in the repo, this is measured on the function, not
parsed from the string. "On front" means some expression on the returned
front passes, whether or not it was selected.

Exhaustive search is capped at size 7 with two constants; it is not run on
Planck in the sweeps (minutes per data set), only in the vocabulary study.

{recovery}

## 6 · The Pareto front and the score

{pareto}

The front is the object to look at, not the selected string. A law shows up
as a large drop in loss at its complexity followed by a flat tail; with
noise the tail is not flat, because extra nodes can always fit some of the
noise, and whether the knee is visible depends on the noise level relative
to the size of the term the law contributes.

## 7 · The operator set is a prior

SR can only return expressions its vocabulary can write. Planck's law needs
`exp` (or `^` with a constant base). Without it, the search returns the best
curve it can build from powers and ratios, and that curve can match the data
closely while failing outside them. This is hypothesis H6 in
`docs/HYPOTHESES.md`; on the real FIRAS data the repo also shows a second,
independent cause, identifiability, with a band-widening control in
`problems/quantum/cmb.py::band_coverage_control`. The experiment here isolates
the vocabulary: same data, same methods, only `exp` (and `log`) removed.

{vocabulary}

The vocabulary is chosen before the search and nothing in the output reports
it. Every SR result should therefore be read together with its operator set,
and a failure to find a law is only informative if the law was expressible.

## 8 · SINDy: sparse regression instead of search

For dynamics `dX/dt = F(X)`, SINDy (Brunton, Proctor & Kutz 2016) replaces
the tree search with linear algebra. Choose a library of candidate terms
`Theta(X) = [1, x, v, x^2, x v, ..., sin x, cos x]`, then solve

    dX/dt = Theta(X) Xi,   Xi sparse

by **sequentially thresholded least squares** (STLSQ): least squares,
zero every coefficient below a threshold, refit on the survivors, repeat.
Columns are normalised first so one threshold means the same for every term
(`sindy.stlsq`). It is fast and deterministic, and it has the same prior as
SR in a different place: the law must be a sparse linear combination of
library terms. A pendulum is found only if `sin(theta)` is in the library.

Its weak point is the left-hand side. `dX/dt` is not measured; it is
estimated from samples. A central difference has truncation error
`O(dt^2)` and noise error `sigma / (sqrt(2) dt)`: at `dt = 0.01` it
amplifies white measurement noise about seventy-fold. A Savitzky-Golay
filter (a local least-squares polynomial, differentiated analytically)
trades that noise for a smoothing bias. Both are measured, with the
convergence study CONTRIBUTING rule 5 asks of any derivative.

Two systems, simulated with DOP853 at `rtol = 1e-12`: a damped oscillator
`x'' + 2 zeta omega x' + omega^2 x = 0` (omega = 2, zeta = 0.1) and a damped
pendulum `theta'' = -(g/L) sin theta - b theta'` (g/L = 9.80665 s^-2,
b = 0.2) started at 2 rad, where `sin theta` is far from `theta`. Noise is
Gaussian with standard deviation `sigma * std(state)`, added to the states.

{sindy}

Two effects are separate here and should not be conflated. The noise that
finite differences add to `dX/dt` is on the left-hand side of a least-squares
problem with a thousand rows, and is largely averaged out. The noise in the
states enters the library `Theta(X)` itself (an errors-in-variables problem),
and the pendulum's library is nearly collinear (`1`, `theta^2` and
`cos theta` are close to dependent over the swing); that is what produces
spurious terms. Smoothing the states as well as the derivative reduces
both effects; the table shows the noise level at which that stops being
enough.

## 9 · AI Feynman, briefly

AI Feynman (Udrescu & Tegmark 2020) attacks the same problem by
divide-and-conquer rather than by search over the whole tree: it fits a
neural network to the data, uses the network as a smooth surrogate to test
for properties such as symmetry, separability (`f(x, y) = g(x) + h(y)` or
`g(x) h(y)`) and dimensional structure, recursively splits the problem into
smaller ones, and only then brute-forces small expressions. Its strength is
on laws with such structure, and it depends on the surrogate being accurate
enough for the tests to be decided, which is a data-quality requirement of
its own.

## References

- M. Cranmer, *Interpretable Machine Learning for Science with PySR and
  SymbolicRegression.jl*, arXiv:2305.01582 (2023).
- S. L. Brunton, J. L. Proctor, J. N. Kutz, *Discovering governing equations
  from data by sparse identification of nonlinear dynamical systems*, PNAS
  113, 3932 (2016).
- S.-M. Udrescu, M. Tegmark, *AI Feynman: a physics-inspired method for
  symbolic regression*, Science Advances 6, eaay2631 (2020).
- J. R. Koza, *Genetic Programming*, MIT Press (1992).
- A. Savitzky, M. J. E. Golay, *Smoothing and differentiation of data by
  simplified least squares procedures*, Anal. Chem. 36, 1627 (1964).
"""


PACKAGES_TEMPLATE = r"""# How the fitting packages do their job

<!-- Generated by physprior.symbolic.report.render_doc() from
     results/symbolic/packages_checks.json. Edit src/physprior/symbolic/text.py. -->

Every arm in this project hands its numbers to a library. This page states
what each library computes, with the mathematics, as read from the installed
versions, and checks the parts that decide the repo's error bars
(`studies.study_packages`). PySR is covered in
[symbolic_regression.md](symbolic_regression.md).

{versions}

## scipy.optimize.curve_fit: the `physics` arm

`curve_fit(f, x, y, p0, sigma, absolute_sigma, bounds, method)` minimises
the weighted sum of squares

    S(theta) = sum_i ((y_i - f(x_i; theta)) / sigma_i)^2 = || r(theta) ||^2

i.e. it whitens the residuals by `sigma` and calls a least-squares solver.

**Which solver.** With no bounds the default is `method="lm"`:
Levenberg-Marquardt as implemented in MINPACK, called through `leastsq`.
With bounds the default is `"trf"`, Trust Region Reflective, through
`least_squares` (`scipy/optimize/_minpack_py.py`). The repo's `fit_physics`
passes bounds for every physical parameter, so **the physics arm runs TRF,
not LM**.

- *Levenberg-Marquardt* takes Gauss-Newton steps damped towards gradient
  descent: `(J^T J + lambda D) delta = -J^T r`, with `J = dr/dtheta`,
  `D` a diagonal scaling and `lambda` adapted each step (large when the
  quadratic model is poor, small near the minimum). It cannot handle bounds.
- *Trust Region Reflective* solves the same Gauss-Newton subproblem inside a
  trust region, with the region shaped by the distance to the bounds and
  steps reflected off them, so iterates stay feasible.

Both converge to the same minimum on a well-posed problem; they differ in
the path and in how bounds are treated.

**The covariance.** Near the minimum `S` is quadratic with Hessian
`~ 2 J^T J` (the Gauss-Newton approximation, dropping second derivatives of
`f`), and the parameter covariance is

    pcov = (J^T J)^-1                          absolute_sigma=True
    pcov = (J^T J)^-1 * S(theta_hat) / (N - p)  absolute_sigma=False

with `J` the Jacobian of the *whitened* residuals. For "lm" MINPACK returns
the inverse; for "trf" SciPy forms it from an SVD of `J`, discarding
singular values below `eps * max(shape) * s_max` (a pseudo-inverse), so a
rank-deficient problem returns a finite but meaningless covariance rather
than `inf` (the documentation says so).

**`absolute_sigma` is a statement about the error bars.**

- `True`: the `sigma` passed in are the true standard deviations. The
  covariance is used as is; a bad fit (reduced chi^2 >> 1) does not inflate
  the error bars.
- `False` (the default): only the *relative* sizes of the `sigma` matter.
  The covariance is rescaled by the reduced chi^2, i.e. the error bars are
  set by the scatter of the residuals.

The repo passes `absolute_sigma=sigma is not None`: measured uncertainties
are trusted when they exist, and the scatter is used when they do not. The
consequence is that a quoted `± sigma` on a real-data constant is only as
right as the data's quoted errors, and a model that is wrong (chi^2/dof >> 1)
is **not** penalised in its error bars. The reduced chi^2
(`benchmark.metrics.chi2_reduced`) is the check, and a large value is a
warning about the law, not something the error bar has absorbed.

{coverage}

With the stated sigma correct, both settings cover near the nominal rate.
With the stated sigma twice the truth, `absolute_sigma=True` believes it and
over-covers; `False` rescales by the residual scatter and recovers the right
interval. By the same arithmetic, understated errors under-cover with `True`.

{jac}

## torch.autograd: the PINN's derivatives

PyTorch builds a graph of the operations applied to tensors that have
`requires_grad=True`, and differentiates it in **reverse mode**: one
backward pass computes the vector-Jacobian product `v^T (dy/dx)` for all
inputs at once, at a cost of a small multiple of the forward pass. With
`v = 1` and a scalar output it is the gradient. `torch.autograd.grad(y, x,
grad_outputs=v)` returns that product without accumulating into `.grad`.

A PINN residual needs `du/dt` (and often `d2u/dt2`) of the network's output
**with respect to its input**, and then the gradient of a loss built from
that derivative **with respect to the weights**. The first derivative is
therefore itself part of the forward computation of the loss, and must be
recorded in the graph. That is what `create_graph=True` does: the backward
pass is executed with graph construction on, so its result can be
differentiated again. Without it the returned derivative is a constant
leaf: a second derivative fails, and a loss built from a first derivative
passes no gradient to the weights through that term.

{grad}

The repo uses `tanh` networks for the same reason: a ReLU network's second
derivative is zero almost everywhere, so a second-order residual would be
identically satisfied (T1 shows this).

## Adam

Adam (Kingma & Ba 2015) keeps exponential moving averages of the gradient
and of its square and steps by their ratio. For gradient `g_t`:

    m_t = beta1 m_(t-1) + (1 - beta1) g_t
    v_t = beta2 v_(t-1) + (1 - beta2) g_t^2
    m_hat = m_t / (1 - beta1^t),   v_hat = v_t / (1 - beta2^t)
    theta_t = theta_(t-1) - lr * m_hat / (sqrt(v_hat) + eps)

with PyTorch defaults `betas = (0.9, 0.999)`, `eps = 1e-8`
(`torch/optim/adam.py`). The bias corrections undo the zero initialisation
of `m` and `v`. The step is `~ lr * sign(g)` whenever the gradient is
consistent, independent of the gradient's scale; this makes Adam robust to
badly scaled losses, and is also why it does not converge to high precision
on its own. The repo follows Adam with L-BFGS (`PinnOptions.lbfgs`) when a
constant has to be recovered to many digits.

{adam}

At a gradient of 1e-6 the step falls short of `lr` by the factor
`g / (g + eps)`: `eps` is not negligible for tiny gradients.

## sympy: from string to function

SR returns a string. `methods/symbolic.py` turns it into something the
scoring code can use in three steps:

- `sympy.sympify(s)` parses the string into an expression tree (with the
  default `convert_xor=True`, a `^` in the string is read as a power);
- `sympy.simplify(e)` rewrites it into a canonical, shorter form for display
  (it is heuristic, and is never used to decide whether a law was found);
- `sympy.lambdify(symbols, e, "numpy")` generates a Python function that
  evaluates the tree with numpy, vectorised.

From there a discovered law is an ordinary numpy function and is scored like
every other arm. Law recovery is decided numerically on that function
(`power_law_exponent`, and `form_check` here), never by comparing strings,
because the same function has many spellings.
"""
